# Numpy Assignment

In [6]:
import numpy as np
list1 = ['1', '2', '3', '4', '5']
array_list = np.array(object = list1)

In [7]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [9]:
type(list1)

list

In [10]:
type(array_list)

numpy.ndarray

The data type is different for both as seen above.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [14]:
print(list1)
for i in list1:
    print(i,':', type(i))

['1', '2', '3', '4', '5']
1 : <class 'str'>
2 : <class 'str'>
3 : <class 'str'>
4 : <class 'str'>
5 : <class 'str'>


In [15]:
print(array_list)
for i in array_list:
    print(i,':', type(i))

['1' '2' '3' '4' '5']
1 : <class 'numpy.str_'>
2 : <class 'numpy.str_'>
3 : <class 'numpy.str_'>
4 : <class 'numpy.str_'>
5 : <class 'numpy.str_'>


In [16]:
array_list1 = np.array(object = list1, dtype = int)

In [18]:
print(array_list1)
for i in array_list1:
    print(i,':', type(i))

[1 2 3 4 5]
1 : <class 'numpy.int64'>
2 : <class 'numpy.int64'>
3 : <class 'numpy.int64'>
4 : <class 'numpy.int64'>
5 : <class 'numpy.int64'>


In [20]:
num_list = [[1,2,3], [4,5,6]]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [23]:
np.shape(num_list)

(2, 3)

In [24]:
np.size(num_list)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])